server:
  port: 8000

spring:
  devtools:
    restart:
      enabled: true  #设置开启热部署
      additional-paths: src/main/java #重启目录
      exclude: WEB-INF/**
  freemarker:
    cache: false    #页面不加载缓存，修改即时生效
  mvc:
    static-path-pattern=/static/**
  resources:
    static-locations=classpath:/static/
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/code_generate?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.jdbc.Driver


# ====================MybatisPlus====================
mybatis-plus:
  global-config:
    configuration:
      map-underscore-to-camel-case: true
    db-config:
      id-type: auto
      field-strategy: not_empty
      table-underline: true
      db-type: mysql
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
#  typeAliasesPackage: com.oa.center.dto.rsp
  mapper-locations: classpath:/mapper/*.xml

api:
  file-create-tmp-path: E:\java-workspace\business-code-generate\temp